name: Auto Push

on:
  schedule:
    - cron: '*/5 * * * *'  # Isso vai rodar a cada 5 minutos
    
jobs:
  push_changes:
    runs-on: windows-latest  # Você pode alterar para windows-latest ou macos-latest, ubuntu-latest, se preferir.

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Git configuration
        run: |
          git config user.name "Igor Gomes"
          git config user.email "igor.gomes.paradella.com"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Atualização automática"
          git push origin main  # Certifique-se de usar a sua branch correta
