name: Auto Push

on:
  schedule:
    - cron: '${{ secrets.CRON_SCHEDULE }}'  # Agora você pode definir a frequência através de um segredo

  workflow_dispatch:  # Permite rodar manualmente a qualquer momento

jobs:
  push_changes:
    runs-on: ${{ secrets.RUNNER_OS }}  # Você pode definir qual sistema usar via um segredo

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Git configuration
        run: |
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "${{ secrets.COMMIT_MESSAGE }}"  # Mensagem do commit configurável
          git push origin ${{ secrets.BRANCH_NAME }}  # Branch configurável
